# Generated by Django 4.2.17 on 2024-12-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_post_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
