# Generated by Django 4.2.17 on 2024-12-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
